### ISSUE TITLE
Should we provide a default implementation of authentication endpoints that's the frontend can consume?

### ISSUE THREAD

**Issue by luzfcb** [labcodes/django-react-webpack#41]
What authentication method should we provide for the frontend?
Session? JWT? Both?

Related links:

https://blog.tinbrain.net/blog/jwt-auth.html
https://blog.tinbrain.net/blog/tokens-aint-tokens.html
https://blog.tinbrain.net/blog/session-auth-spa.html

**Comment by CavalcanteLucas** [comment]
Closed in favor of https://github.com/labcodes/django-react-webpack/issues/33
