### ISSUE TITLE
Migrate react code to react hooks

### ISSUE THREAD

**Issue by lucianoratamero** [labcodes/django-react-webpack#55]
Since react hooks are the industry standard, it would be nice for us to use react hooks instead of class based components in this project.
That would also mean changing a bit of our testing stach, that still uses enzyme, to something more modern and compatible, like react testing library.

Another good thing would be to migrate all component js files to jsx, since it's the more proper file extension.

**Comment by Archit0123** [comment]
I can help with this issue.
